baseURL = "https://andrew.io"
languageCode = "en-us"
title = "Andrew's Notes"
theme = "PaperMod"

[params]
  env = "production"
  description = "Notes on Agentic AI and Coding"
  author = "Andrew"
  
  # Home page
  homeInfoParams.Title = "Andrew's Notes"
  homeInfoParams.Content = "Thoughts and learnings on Agentic AI for coding"
  
  # Social links (optional)
  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/yourusername"

# Menu
[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
name = "Archive"
url = "/archive/"
weight = 20

[[menu.main]]
name = "Search"
url = "/search/"
weight = 30
