baseURL = "https://andrew.io"
languageCode = "en-us"
title = "Andrew's Notes"
theme = "PaperMod"

[params]
  env = "production"
  description = "Andrew's Notes"
  author = "Andrew"
  
  # Home page
  homeInfoParams.Title = "Andrew's Notes"
  homeInfoParams.Content = "Thoughts and learnings"
  
  # Social links (optional)
  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/andrewwatts"

  # Enable search
  fuseOpts.keys = ["title", "permalink", "summary", "content"]


# Menu
[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
name = "Archive"
url = "/archive/"
weight = 20

[[menu.main]]
name = "Search"
url = "/search/"
weight = 30
